platform :ios, '8.0'

use_frameworks!
target 'SwiftDemo' do

    pod 'RxSwift', '~> 4.0.0’
    pod 'SnapKit', '~> 4.0.0’
    pod 'CryptoSwift', '~> 0.7.1’
    pod 'Alamofire', '~> 4.5.1’
    pod 'ObjectMapper', '~> 3.0’
    pod 'SwiftyAttributes', '~> 4.0.0’
    pod 'Kingfisher', '~> 4.0’
    pod 'MonkeyKing', '~> 1.4.0’
    pod 'LTMorphingLabel'
    pod 'Charts'
    pod 'MJRefresh'
    pod 'AFNetworking', '~> 3.0'

end
